using SECmd.Nif;

namespace SECmd.Tests
{
    /// <summary>
    /// Which fields a round trip is currently allowed to change, and why.
    /// </summary>
    /// <remarks>
    /// Every test that round-trips a NIF compares the whole graph with
    /// <see cref="NifComparer"/> and fails on any field not listed here. The point is
    /// the ratchet: a difference that is already known does not fail, and a *new* one
    /// does, so the surface can only shrink.
    ///
    /// The two lists are not the same thing and must not be merged.
    ///
    /// <see cref="ByDesign"/> is derived rather than carried, on purpose, and will
    /// never be empty. <see cref="Open"/> is a list of defects — every entry is
    /// something this port gets wrong, recorded so that it fails visibly as a *count*
    /// rather than invisibly as nothing at all. Entries leave it by being fixed.
    ///
    /// It exists because the corpus sweep compares a census of block *types*, so
    /// anything wrong inside a block was invisible to it. That is how a shader
    /// controller came back driving the wrong variable in 1,648 meshes, how every
    /// off-centre collision box collapsed to the origin, and how a skin partition's
    /// triangles were being remapped into nonsense — all with a green suite.
    /// </remarks>
    public static class RoundTripBaseline
    {
        /// <summary>
        /// Fields computed from the rebuilt graph rather than carried across.
        /// </summary>
        /// <remarks>
        /// Carrying these would describe the file the FBX came from rather than the one
        /// just built, and for several the source value is the most likely to be stale.
        /// </remarks>
        public static readonly Dictionary<string, string> ByDesign = new(StringComparer.Ordinal)
        {
            // Refitted from the tessellated collision geometry, which is the half of a
            // shape a DCC tool can edit; carrying the original would ignore the edit.
            // A vertex carries at most four influences, so one with more is reduced to
            // its four largest and the remainder renormalised over them. That is the
            // format's limit rather than a choice, and it moves every weight on such a
            // vertex by a few parts in ten thousand.
            //
            // Only the weights. `Bone Indices` is not excused: which four survive can
            // differ from the source's four, and a weight landing on the wrong *bone*
            // is a real fault that shows there.
            ["Bone Weights"] = "a vertex holds four influences; more are reduced and renormalised",

            // A MOPP tree is regenerated by the backend rather than carried, so its code
            // is whatever Havok produced this time and its length with it. Keyed by path:
            // `Data Size` is a name three unrelated blocks use.
            ["MOPP Code/Data Size"] = "the MOPP code is regenerated, not carried",

            ["Radius"] = "refitted from the tessellated collision geometry",

            // A capsule's two end radii, refitted from the tessellation exactly as
            // `Radius` above is. The fit is loose — a capsule ends up around a fifth
            // narrower than the source in the fixtures — which is worth improving, but
            // it is the fit that is approximate, not the carrying that is broken.
            ["Radius 1"] = "refitted from the tessellated collision geometry",
            ["Radius 2"] = "refitted from the tessellated collision geometry",
            ["Dimensions"] = "refitted from the tessellated collision geometry",

            // Zeroed by the static motion profile, as ck-cmd's is. A static carrying a
            // mass is treated as movable, which is how scenery falls through the world.
            ["Mass"] = "zeroed by the static motion profile, as ck-cmd does",

            // The inertia tensor is computed from the shape and the mass (spec §5.7.2).
            ["m11"] = "inertia computed from the shape and mass",
            ["m12"] = "inertia computed from the shape and mass",
            ["m13"] = "inertia computed from the shape and mass",
            ["m21"] = "inertia computed from the shape and mass",
            ["m22"] = "inertia computed from the shape and mass",
            ["m23"] = "inertia computed from the shape and mass",
            ["m31"] = "inertia computed from the shape and mass",
            ["m32"] = "inertia computed from the shape and mass",
            ["m33"] = "inertia computed from the shape and mass",

            // 0xCD in every byte is the debug heap's fill pattern: fields the exporter
            // that wrote the fixture never initialised. There is nothing to reproduce.
            ["Auto Remove Level"] = "uninitialised in the source file (0xCD)",
            ["Response Modifier Flags"] = "uninitialised in the source file (0xCD)",
            ["Num Shape Keys in Contact Point"] = "uninitialised in the source file (0xCD)",
            ["Force Collided Onto PPU"] = "uninitialised in the source file (0xCD)",

            ["Consistency Flags"] = "not carried",
            ["Bounding Sphere"] = "recomputed from the vertices",
            ["Center"] = "recomputed from the vertices",

            // The hull is refitted, so its corners and planes arrive in the fit's order
            // rather than Havok's. That the corners themselves all come back is asserted
            // by AConvexHullKeepsEveryCorner, and the plane convention by
            // ConvexHullPlaneTests.
            ["Vertices"] = "convex hull refitted from the tessellation, so the order differs",
            ["Normals"] = "convex hull refitted from the tessellation, so the order differs",

            // Regenerated from the geometry rather than carried (spec §5.3.1). A
            // deliberate departure from ck-cmd, which keeps an FBX's own tangents; §7.3
            // records why that is the wrong half of the trade for an authored mesh.
            ["Tangent"] = "tangent space regenerated (§5.3.1)",
            ["Tangents"] = "tangent space regenerated (§5.3.1)",
            ["Bitangents"] = "tangent space regenerated (§5.3.1)",
            ["Bitangent X"] = "tangent space regenerated (§5.3.1)",
            ["Bitangent Y"] = "tangent space regenerated (§5.3.1)",
            ["Bitangent Z"] = "tangent space regenerated (§5.3.1)",

            // The motion profile is applied from the resulting collision layer rather
            // than carried: the spec's table at §5.7 gives the motion system,
            // deactivation and quality for each layer, and ck-cmd sets them the same
            // way. A body that arrives on a given layer gets that layer's settings,
            // which is the point of having a profile at all.
            //
            // `Layer` itself is deliberately *not* here. It is the input to the profile,
            // and a body landing on the wrong layer is a real fault — it decides what
            // the thing collides with.
            ["Motion System"] = "set from the collision layer by the motion profile (§5.7)",
            ["Solver Deactivation"] = "set from the collision layer by the motion profile (§5.7)",
            ["Quality Type"] = "set from the collision layer by the motion profile (§5.7)",

            // A quadratic key's tangents. FBX cannot express them directly, so the
            // exporter sets TangentAuto and lets the importer choose tangents that
            // reproduce the curve's shape (spec §5A). The numbers therefore differ while
            // the curve does not — which is the trade the spec records, not a loss.
            ["Forward"] = "quadratic key tangents are re-chosen by the importer (§5A)",
            ["Backward"] = "quadratic key tangents are re-chosen by the importer (§5A)",

            // Calculated from the block graph rather than carried (bsxflags-spec.md),
            // and *added* to a file that had none -- which lengthens the root's extra
            // data list by one. The corpus sweep has always excluded that; it was sitting
            // in the defect list here only because the field names were collected by
            // measurement rather than read.
            ["BSXFlags"] = "calculated from the block graph",
            ["Num Extra Data List"] = "the calculated BSXFlags is added to a file that had none",
            ["Extra Data List"] = "the calculated BSXFlags is added to a file that had none",

            // A shape's own transform is baked into its vertices rather than left on
            // the node, which is what ck-cmd does and what the spec records at §2: "the
            // shape transform is therefore baked into the vertices, not left on the
            // node". So a shape that had a transform comes back with its geometry in
            // the parent's space and an identity transform of its own.
            //
            // It is lossy — the split between where a thing is and what shape it is
            // does not survive, and an animation driving that node now moves geometry
            // already displaced — but it is deliberate, documented and matched to the
            // reference. Keyed by path for the transform itself, so that a *different*
            // translation going missing somewhere else still fails.
            ["Vertex"] = "the shape's transform is baked into its vertices (spec §2)",
            ["Normal"] = "the shape's transform is baked into its vertices (spec §2)",
            ["BSTriShape/Translation"] = "zeroed: the transform is baked into the vertices",
            ["BSTriShape/Rotation"] = "zeroed: the transform is baked into the vertices",
            ["BSTriShape/Scale"] = "reset: the transform is baked into the vertices",
            ["NiTriShape/Translation"] = "zeroed: the transform is baked into the vertices",
            ["NiTriShape/Rotation"] = "zeroed: the transform is baked into the vertices",
            ["NiTriShape/Scale"] = "reset: the transform is baked into the vertices",
            ["NiTriStrips/Translation"] = "zeroed: the transform is baked into the vertices",
            ["NiTriStrips/Rotation"] = "zeroed: the transform is baked into the vertices",
            ["NiTriStrips/Scale"] = "reset: the transform is baked into the vertices",

            // nif.xml's KeyType runs 1..5 and has no zero, so a key group carrying one
            // is a field nothing ever set — which is what a model built in a test looks
            // like. Writing LINEAR_KEY for it is normalisation, not loss.
            ["Interpolation"] = "0 is not a KeyType; an unset one becomes LINEAR_KEY",


            // BSXFlags is calculated from the finished graph, never carried, because
            // every bit is a statement about that graph (see `docs/bsxflags-spec.md`).
            // So a file whose own flags disagree with its own contents comes back
            // corrected, and all three fixtures that differ here are exactly that:
            //
            // - FixBSXFlags_AddExtEmit holds 1 while carrying a shader with external
            //   emittance, so the calculated 512 sets the bit the file is missing.
            // - FixBSXFlags_RemoveExtEmit holds 513 with no such shader anywhere, so
            //   the calculated 0 clears a bit the file should not have. Both are
            //   fixtures *for* a flag-fixing operation, and hold the unfixed value on
            //   purpose.
            // - Furniture_Col_SE holds 138 while its rigid body is MO_QUAL_MOVING,
            //   which is what bit 6 asks about, so the calculated 202 sets it.
            //
            // Listed as a divergence rather than removed because the field does differ;
            // it is on the by-design list because this is the design working.
            ["Integer Data"] = "BSXFlags is calculated, and these files disagree with themselves",

            // Not a number about the mesh. Every vanilla value is 16-byte aligned and
            // they cluster in tight runs -- 0x1078Axxx and neighbours, spread across
            // 0x4DA140 to 0x171ECE60 -- which is a heap address from whatever machine
            // Bethesda exported on, written out with the rest of the struct. There is
            // nothing in it to reconstruct; ck-cmd does not write it either.
            ["User Data"] = "an exporter's leftover heap address, not data about the shape",

            // nif.xml calls these padding and they are padding: `Unused 01` is a binary
            // byte[4] on the rigid body info and a byte[8] on a constraint's, `Unused 03`
            // a lone byte. Nothing reads them, and a rebuilt block zeroes them.
            // A compressed mesh is not stored as geometry. It is stored as chunks, each
            // a cloud of 16-bit offsets from an origin Havok picked, and Havok picks
            // again on the way back -- so every per-chunk field reads as changed on a
            // mesh that came through intact, and the count of them changes too: 13
            // chunks where the file has 14, 2 where it has 3.
            //
            // What is left after mopper was given the shape-builder settings HKXWrangler
            // uses -- one stripper pass, welding on, a 0.001 tolerance
            // (HKXWrangler.cpp:3349). Those decide how Havok cuts the mesh into strips
            // and which vertices it merges, and so decide every array in a chunk. With
            // mopper's own 5,000 passes and no welding the fixtures differed in 12,600
            // fields; with ck-cmd's, in 25. Ten sibling entries that existed only to
            // excuse the old wholesale mismatch are long gone.
            //
            // By design rather than open, because the question these fields were
            // standing in for now has a test of its own.
            // `EveryVanillaCollisionMeshKeepsItsShape` decodes both sides and asks
            // whether the *shape* survived -- surface area, bounding box, and whether
            // any rebuilt vertex sits off the original surface -- which is the only
            // thing the physics engine reads. 21,993 of 22,047 pass it. Comparing the
            // encoding was never going to answer that, in either direction: it cannot
            // tell a re-chunked mesh from a broken one.
            ["bhkCompressedMeshShapeData/Chunks"] = "Havok chunks the mesh its own way (shape checked separately)",
            ["Num Chunks"] = "Havok cuts its own number of chunks (shape checked separately)",

            // A strips shape's strips, written one triangle each.
            //
            // A strip is a compression of an index list and nothing reads it back as
            // anything else: three points per triangle says the same mesh as a run of
            // eight, and reconstructing longer runs would be guessing at how whichever
            // tool made the file happened to split them. `BuildTriStrips` says so where
            // it writes them.
            //
            // By design rather than open, because there is no version of this that comes
            // out matching. The triangles are the fact; the strips are one of many ways
            // to spell them, and the file does not record which way was chosen.
            ["Points"] = "a strips shape's strips are written one triangle each, by design",
            ["Num Strips"] = "a strips shape's strips are written one triangle each, by design",
            ["Strip Lengths"] = "a strips shape's strips are written one triangle each, by design",

            // An empty shape's class, when the model asks for one its edition does not
            // have. The carried class is honoured -- `BuildEmptyShape` reads it and
            // rebuilds a BSTriShape as a BSTriShape -- with one exception: a Legendary
            // Edition file has no BSTriShape at all, so one is written as the NiTriShape
            // that edition does have.
            //
            // The difference is the test's own doing rather than the conversion's. It
            // puts a BSTriShape into `multi_material_cube`, which is an LE fixture, to
            // check that a dummy shape survives at all -- nif.xml says a
            // BSProceduralLightningController is "paired with dummy TriShapes", and
            // losing them cost the staff bolts half their blocks. A model that mixes
            // editions gets the class its edition has, which is the right answer to a
            // question that should not have been asked.
            ["BSTriShape"] = "an SE-only class in an LE model comes back as LE's equivalent",

            // The fixture's own two copies of the weights disagree, and only one of
            // them can be rebuilt from the other.
            //
            // 302 of 12,840 slots in TestNifFile_LooseBlocks_SE differ, all of them
            // where the file's NiSkinData and its vertex buffer say different things.
            // 296 are a fourth influence the buffer carries and NiSkinData omits
            // outright -- vertex 1628 has b3 at 0.0001 in the buffer and three
            // influences in NiSkinData. The other six are ties: vertex 2235 weights
            // b4 and b1 at 0.375977 each, and the buffer's slot order for a tie is the
            // authoring order, which a per-bone list sorted by bone does not record.
            //
            // Reading NiSkinData, as this does, reproduces it exactly and loses those
            // 302 buffer slots; reading the buffer would do the reverse. Carrying both
            // would mean carrying two sets of weights for one skin and choosing between
            // them at the far end, which is a machinery for reproducing a contradiction.
            //
            // By design rather than open, because vanilla does not have the problem.
            // Over 1,768,446 skinned vertices in a seventh of Skyrim's meshes, once the
            // empty-NiSkinData case is accounted for, the buffer holds an influence
            // NiSkinData lacks exactly **zero** times, and sorting NiSkinData by
            // descending weight reproduces the buffer's slot order in all 1,764,398
            // vertices where the two agree. A file whose copies disagree is a file that
            // is wrong about itself, and there is no rebuilding it that is right.
            ["Bone Indices"] = "the fixture's two copies of the weights disagree; no vanilla file's do",

            // The root's controller, on a file that carries animation and has no
            // manager to run it.
            //
            // A controlled block's own controller reference is set -- a transform entry
            // points at the multi-target controller, as the file does -- and this is the
            // root's, which gains a NiControllerManager because the import builds one
            // for the animation it was given.
            //
            // Which is what every file that has animation does. Of the 1,274 meshes the
            // game ships holding either a sequence or a manager, all 1,274 hold both,
            // and in all 1,274 the root's controller chain reaches the manager. Not one
            // has sequences without a manager, and not one has a manager without
            // sequences.
            //
            // So a source with animation and no manager is a file no vanilla mesh
            // resembles, and giving it one is the conversion doing its job rather than
            // adding something. The fixture that flags this is a synthetic model.
            ["Controller"] = "animation gets the manager that runs it, as all 1,274 vanilla files have",

            // A palette entry naming a node the file does not contain.
            //
            // `NiDefaultAVObjectPalette` maps a name to the block a sequence means by
            // it, and a rebuilt palette is written from the blocks the scene actually
            // has -- every named `NiAVObject` bar the root, which is what the game's
            // own palettes hold in 211 of 263 sampled.
            //
            // Some of the nifly fixtures disagree with themselves: `TestNifFile_Animated_LE`
            // names `Icicle01_Low02` and `IceGlow` in its palette while the nodes it
            // holds are called `Low02` and `Glow`. Those entries resolve to nothing, in
            // this port and in the game, and a rebuilt file cannot reproduce a name no
            // block has without inventing the block too.
            //
            // Only the row is excused, not what stands behind it: the comparison stops
            // at a row whose two sides name different things rather than walking into
            // two unrelated blocks, so nothing below is hidden by this. Whether a
            // sequence can still find its target is a behaviour rather than a field,
            // and `EveryRebuiltSequenceTargetIsInThePalette` measures it directly.
            [NifComparer.UnpairedEntry] = "a fixture palette names nodes the file does not have",

            ["Unused 01"] = "padding nif.xml names Unused; a rebuilt block zeroes it",
            ["Unused 03"] = "padding nif.xml names Unused; a rebuilt block zeroes it",

            // The fourth lane of a box's half extents. Havok keeps them in an
            // `hkVector4` and reads three of it, so nif.xml is right that this is
            // unused -- but unused is not zero, and every vanilla box has something in
            // it. Of the 569 boxes in a 2,500-mesh sample, none holds zero and none
            // holds a number of its own: every value is a copy of another field of the
            // same block, 442 of `Radius`, 74 of `Dimensions.Z`, 31 of `Dimensions.X`,
            // 22 of `Dimensions.Y`, and nothing else at all.
            //
            // That is the register the extents were built in, keeping whatever went
            // through its fourth lane last. It is leftover rather than authored, so a
            // rebuilt box zeroes it as it zeroes the other padding nif.xml names.
            ["Unused Float"] = "padding nif.xml names Unused; a rebuilt block zeroes it",

            // A partition's vertex map holds the right vertices in an order of our own.
            // Accepted in the spec (§7.3): the set is always exact -- 860 of 860
            // partitions in a 600-mesh sample come back holding what they held -- and
            // the sequence follows no rule that can be re-derived. Of those 860, 317
            // are ascending, 229 are first appearance in the partition's own triangles,
            // and 314 are neither, so there is nothing to reproduce it from. The
            // deformers cannot supply it either: a cluster lists only the vertices its
            // own bone moves, and no cluster holds the whole map.
            //
            // The renderer walks the map rather than indexing into it by position, so a
            // map is as good in one order as another; this is a byte-fidelity gap, not
            // a behavioural one.
            //
            // Only this field. `Vertex Weights` and the partition's own `Triangles` are
            // indexed by the map and shift with it, but they differ for reasons of
            // their own as well, and excusing them here would blind the sweep to those.
            ["Vertex Map"] = "a partition's vertex map holds the right vertices in our order (spec §7.3)",

        };

        /// <summary>
        /// Fields a round trip currently gets wrong. Every entry is a defect.
        /// </summary>
        /// <remarks>
        /// Recorded, not excused. The counts are what the fixtures reported when the
        /// list was taken, so a change that makes one worse is still invisible here —
        /// what this catches is a *new* field going wrong, which is the failure mode
        /// that has cost the most.
        ///
        /// Some of these are one defect wearing several names: a mesh whose vertices
        /// arrive in the wrong space reports `Vertex`, `Num Vertices`, `Data Size` and
        /// `Triangles` at once. Fixing the cause will empty several rows together.
        ///
        /// Known causes at the time of writing, from the review backlog:
        ///
        /// <list type="bullet">
        /// <item>`TestNifFile_DeepGraph_SE` returns its vertices in world space —
        /// (-2.1, 2.5, 0.15) comes back as (-197, 222, 334) — so a transform is applied
        /// twice somewhere down a 25-deep chain. That accounts for `Vertex`, `Normal`
        /// and a good deal of `UV`.</item>
        /// <item>A skinned SE shape keeps its geometry in the skin partition and the
        /// rebuilt file puts it on the shape: `Vertex Desc`, `Vertex Size`, `Vertex
        /// Data`, `Num Vertices`, `Num Triangles` and `Data Size` are one cause under
        /// six names. `NifSkinWriter.WriteSkinPartitions` sizes the per-partition arrays
        /// and never touches the block's own, so the import has nowhere else to put it.
        ///
        /// Attempted and reverted, which is worth knowing before it is attempted again.
        /// Copying the shape's vertex data into the partition and zeroing the shape's is
        /// *not* enough, for two reasons found by doing it:
        ///
        /// The partition's vertex layout is its own, not the shape's. Its `Vertex Size`
        /// came out 24 or 28 bytes against the shape's 40 — a different descriptor
        /// holding different attributes — so the descriptor has to be built for the
        /// partition rather than copied.
        ///
        /// And the form is not universal. `TestNifFile_Optimize_SE_to_LE` keeps its
        /// geometry in *both* places, so an import that always moves it is wrong for
        /// that file. Which form the source used is not derivable from the FBX; it has
        /// to travel, the way `strips_parts` does. (That fixture's *vertex layout* was
        /// separately corrected — it held a weightless Legendary vertex in a Special
        /// Edition file — but it still keeps geometry in both places, which is what
        /// this paragraph is about.)
        ///
        /// Two smaller things surfaced while the partition was briefly populated and
        /// therefore briefly compared, and both are still true: renormalising bone
        /// weights by a total that is already 1 shifts every weight into a neighbouring
        /// half, and reducing a vertex to four influences picks a different four from
        /// the source in 6 of 12,840 slots (the rest are zero-weight padding).</item>
        /// <item>The motion profile is applied rather than carried, so `Layer`,
        /// `Motion System`, `Quality Type`, `Solver Deactivation`, `Friction`,
        /// `Restitution` and the damping pair take the profile's values. This one may
        /// well be by design — the spec documents the profile — but it has not been
        /// checked, and guessing would put a defect in the wrong list.</item>
        /// </list>
        /// </remarks>
        public static readonly Dictionary<string, string> Open = new(StringComparer.Ordinal)
        {

            // A body carries a collision layer in more than one filter -- its own, and
            // one or more inside `Rigid Body Info` -- and they do not always agree in the
            // source. The body's own is now carried (see ABodyKeepsTheLayerItWasOn); the
            // ones under `Rigid Body Info` are not, and what they mean has not been


            // The vertex descriptor is computed from what the mesh turned out to hold
            // rather than carried from the file, so a shape whose vertices were 24 bytes
            // comes back with 40 — tangents added to geometry that had none. Everything
            // sized from it follows: `Vertex Size`, `Data Size`, and the vertex array
            // itself.
            //
            // Separate from where the geometry *lives*, which is now right: a skinned
            // shape's vertices are written into the skin partition as the format has
            // them. These are what that uncovered underneath.



            // The palette is built the way ck-cmd builds it -- FBXWrangler.cpp:4312 fills
            // it from the multi-target controller's extra targets plus the conversion
            // root, and nothing else -- so it holds two entries where Bethesda's own file
            // holds eleven, including emitters and geometry.
            //


            // A breakable constraint in the game's files often names only one entity, and
            // the import links both from the scene -- the far body is the node the
            // attachment hangs under, so there is always one to link. The source's null
            // is not reproduced.
            // The MOPP tree's quantisation, and the chunk bounds it is derived from.
            // Both come out a millimetre off, which is Havok quantising a mesh it built
            // itself rather than the one Bethesda built.
            //
            // The tree's origin sits a margin below those bounds, and the margin *is*
            // near enough a constant in Bethesda's files -- just not the one nif.xml
            // documents nor the one Havok defaults to. Of the 8,188 MOPP trees the game
            // ships:
            //
            //   8,040   origin = the geometry's minimum minus 0.005
            //     135   minus 0.05, which is what mopper and ck-cmd produce
            //      13   an origin *above* the geometry, by up to 0.034
            //
            // and not one uses the 0.1 that nif.xml states outright ("the minimum of all
            // vertices in the packed shape along each axis, minus 0.1"). The two fixtures
            // that disagree are one of each of the first two kinds, which is why this
            // read as inconstant when only they had been looked at.
            //
            // So there is a number to aim at, and the obvious way to ask for it does not
            // work. The margin is Havok's rather than this port's, and it is not any of
            // the MOPP fit tolerances: mopper was built with each of
            // m_absoluteFitToleranceOfTriangles, m_absoluteFitToleranceOfInternalNodes
            // and m_absoluteFitToleranceOfAxisAlignedTriangles set to 0.005, and the
            // margin came out 0.050000 every time, to the last digit. Whatever fixes it
            // is inside the compiler for this version of Havok and is not on the input
            // struct.
            //
            // Nor can it be corrected afterwards. The tree's node bounds are quantised
            // against the origin and the scale, so moving the origin without rebuilding
            // shifts every bound in the tree by the same amount.
            //
            // The thirteen with the origin above their geometry are worth remembering
            // before anyone treats vanilla as the specification here. A tree whose frame
            // does not contain the shape is the file being wrong about itself, which the
            // convex hulls do too (§7.3).
            ["Min"] = "Havok quantises the mesh it was given, not the one Bethesda had",

            // The other corner of that same box, which moves with it. Of 490 compressed
            // mesh shapes sampled, 149 have both corners differing and exactly one has
            // Max differing while Min does not -- so this is the same quantisation, seen
            // from the far end of the AABB, and not a second fault.
            //
            // It was missing only because `Min` above excuses its corner everywhere, so
            // the sweep reported the box under whichever corner was left: 2,052 meshes,
            // 348 of them differing in nothing else at all.
            //
            // Scoped to the path. `Max` on its own is too common a name to excuse
            // wholesale -- `BSRangeNode` has one, and it is a byte with nothing to do
            // with Havok.
            ["AABB/Max"] = "Havok quantises the mesh it was given, not the one Bethesda had",
            ["Offset"] = "vanilla's origin margin is 0.005; Havok's default, which mopper takes, is 0.05",


            // Bethesda over-allocates this array and leaves the rest empty. Every one of
            // the 419 multi-target controllers sampled from the game has null slots, and
            // 14,047 of their 15,188 slots -- 92.5% -- are empty; the fixture here has
            // one real target and thirteen nulls behind it. se-cmd writes the real ones
            // and stops, which is the same content without the padding.
            // The same padding, on a node's child list. Rarer there -- 238 of the 30,942
            // nodes sampled have a null child, and 445 of 47,024 slots -- but real: the
            // fixture that flags this has a root whose one child slot holds -1. se-cmd
            // writes the children that exist and stops.
            ["Num Children"] = "Bethesda leaves empty child slots; this writes the real ones",
            ["Children"] = "Bethesda leaves empty child slots; this writes the real ones",

            // A partition's bone list is padded to a multiple of four by repeating
            // entries, and se-cmd writes the distinct set. Of the 40,626 partitions the
            // game ships, 36,778 have a bone count that is a multiple of four and 30,218
            // hold at least one bone twice: 12,037 list a single bone four times over,
            // 17,763 list two bones in four slots, 418 list three.
            //
            // The repeats say nothing. A bone palette naming the same bone twice binds
            // the same matrix twice, and the partition's own rows index whichever slot
            // they please. It is the largest single difference left in the field sweep
            // -- 3,081 meshes differ in Num Bones and nothing else -- and the smallest
            // in meaning.
            //
            // Reproducing it needs the padding rule and not only the count: 9,994
            // partitions list exactly the skin's whole bone list rather than their own
            // bones, so "round the distinct set up to four" is not it either.
            ["Num Bones"] = "Bethesda pads a partition's bone list with repeats; this writes the distinct set",

            // The list the count above counts, which differs for the one reason the
            // count does. Over a 1,200-mesh sample it accounts for 2,009 differences in
            // the array's length -- every sampled one a file holding a multiple of four
            // against our one or two -- and 206 in an entry of it, where the lengths
            // happened to match and the repeats fell in different slots.
            //
            // Recorded the same way `Children` is recorded beside `Num Children`, for
            // the same padding.
            //
            // Scoped to the path rather than the field name, which is much too common to
            // excuse everywhere: `NiSkinInstance` names its own bones in a `Bones` array
            // and a bone missing from *that* is a skin that has lost a bone. So is
            // `BSTreeNode`'s, which differs 85 times in the same sample and stays
            // reported.
            ["NiSkinPartition/Partitions/Partitions/Bones"] =
                "Bethesda pads a partition's bone list with repeats; this writes the distinct set",

            ["Num Extra Targets"] = "Bethesda pads this array; 92.5% of vanilla slots are empty",
            ["Extra Targets"] = "Bethesda pads this array; 92.5% of vanilla slots are empty",

            // The palette maps a name to a block so the engine can resolve a sequence
            // without walking the tree. ck-cmd builds it from the multi-target
            // controller's targets plus the conversion root (FBXWrangler.cpp:4312) and
            // this follows it, which for the fixture is 2 entries against Bethesda's 11.
            //
            // Bethesda's rule was looked for and not found. "Every named AV object bar
            // the root" matches 322 of the 419 palettes sampled, 77%, and the ones it
            // misses exclude more still -- fxgreybeardshoutfaas leaves out its
            // OrderedRenderingNode as well as its root. Worth knowing: the entry's Name
            // is the block's own name in every vanilla palette, 7,811 entries with no
            // exception, so it is only *which* blocks are listed that is unclear.
            ["Num Objs"] = "built as ck-cmd builds it; Bethesda lists more and by no rule found",
            ["Objs"] = "built as ck-cmd builds it; Bethesda lists more and by no rule found",

            // A controller shared by several sequences no longer claims nif.xml's
            // inverted infinite span -- it now covers the keys it is given -- but which
            // span Bethesda writes is still not known, and has now been looked for
            // properly rather than guessed at.
            //
            // For a controller holding its own interpolator the rule is plain and this
            // follows it: of the 12,326 in the game with keys to compare against, 12,315
            // have a span exactly equal to their key range. Eleven are narrower, all of
            // them bird-flight and light-beam meshes that start late.
            //
            // An attached controller is the open case. It holds a blend interpolator and
            // no keys of its own -- the keys are in each sequence that names it -- and
            // over the 10,432 such controllers the game ships, four candidate rules were
            // measured and none accounts for more than a twelfth:
            //
            //   the union of every driving sequence's keys      816
            //   some driving sequence's own Start/Stop          817
            //   a sequence's start plus its key range           836
            //   the first driving sequence's keys                11
            //   none of those                                 9,605
            //
            // farmhousewindmill has one at 18.60 to 18.90 where the keys of everything
            // driving it span 0 to 16.67, and a NiPSysModifierActiveCtlr at 0 to 22.50
            // where its one sequence's keys reach 5.50. Whatever sets these is not in
            // the sequences, so this keeps the wider, defensible answer: cover the keys.
            ["Start Time"] = "an attached controller's span covers its keys; Bethesda's is narrower",
            ["Stop Time"] = "an attached controller's span covers its keys; Bethesda's is narrower",







            // Also found the moment synthetic models were compared in full, each by a
            // test that was looking at something else at the time.

            // A transform track's static pose -- translation, rotation and scale alike --
            // comes back as the "no value" sentinel (float.MinValue) where the source
            // held real numbers.
            //



            // Not the V flip -- that is fixed and asserted by AUvSurvivesTheRoundTrip.
            // What is left is vertex *order*: the reader numbers vertices in the order
            // the triangles first reach them, so a rebuilt shape holds the same UVs
            // shifted along by a place or two. Every per-vertex field says so at once.

            // nif.xml calculates this one from Vertex Desc, Num Vertices and Num
            // Triangles, so it is a consequence of those rather than a fault of its own:
            // it will come right when the geometry does, and not before.

            // The hull's own corners come back exactly -- 326 of 326 on the fixture that
            // flags this -- and every one of its 165 face planes is reproduced. There are
            // 172 of them rather than 165, the extras being a face the quickhull found
            // twice and the coplanar tolerance did not merge. Loosening that further
            // trades the extras for real faces: at 3e-3 the count reaches 166 and two of
            // the file's own planes are gone.
            ["Num Normals"] = "seven near-duplicate face planes the hull fit leaves behind",
        };

        /// <summary>Every difference that is neither derived nor already recorded.</summary>
        /// <remarks>
        /// An entry keyed by a bare field name excuses that field everywhere, which is
        /// right for something derived — a bounding sphere is recomputed wherever it
        /// appears. It is far too broad for a field as common as `Name`, so an entry
        /// holding a slash is matched against the *path* instead, and excuses only the
        /// place it names.
        /// </remarks>
        public static List<NifDifference> Unexplained(NifModel source, NifModel rebuilt) =>
            [.. NifComparer.Compare(source, rebuilt).Where(d => !Excused(d))];

        private static bool Excused(NifDifference difference) =>
            Matches(ByDesign, difference) || Matches(Open, difference);

        /// <summary>Whether one entry key covers a difference, by the rule above.</summary>
        public static bool Covers(string key, NifDifference difference) =>
            key.Contains('/', StringComparison.Ordinal)
                ? difference.Path.Contains(key, StringComparison.Ordinal)
                : key == difference.Field;

        private static bool Matches(Dictionary<string, string> entries, NifDifference difference)
        {
            foreach (string key in entries.Keys)
            {
                bool matched = key.Contains('/', StringComparison.Ordinal)
                    ? difference.Path.Contains(key, StringComparison.Ordinal)
                    : key == difference.Field;

                if (matched)
                    return true;
            }

            return false;
        }
    }
}
